apiVersion: batch/v1
kind: Job
metadata:
  name: iperf-client-job
spec:
  parallelism: 3
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
      restartPolicy: Never
      containers:
      - name: iperf-client
        image: moutten/iperf:2.0
        args: ['-c', "__ip__"]
