apiVersion: v1
kind: PersistentVolume
metadata:
  name: ceph-client-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/results
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-client-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ceph-client-tests-job
spec:
  template:
    spec:
      restartPolicy: Never
      volumes:
      - name: ceph-client-storage 
        persistentVolumeClaim:
          claimName: ceph-client-volume-claim
      nodeSelector:
        kubernetes.io/hostname: node4
      containers:
      - name: ceph-client
        image: jcnitdgp25/ceph-client:latest
        volumeMounts:
          - name: ceph-client-storage
            mountPath: /workspace
